name: Deploy

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: sa-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      STAGE: prd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm i serverless -g
      - run: npm install @prisma/client -g
      - run: npx prisma generate
      - run: npm run build
      - run: serverless deploy --verbose
